name: HACS validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate as a Dashboard plugin
        uses: hacs/action@main
        with:
          category: plugin
